# Site settings
title: Ruth Garbus
email: julia.h.bodian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The home for all things Ruth Garbus.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rrrugaaa
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed

include:
  - static

collections:
  categories:
    output: true
  music_releases:
    output: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
